language: go
go_import_path: github.com/ethereum/go-ethereum
jobs:
  include:
    - stage: build
      if: type = push
      os: linux
      arch: amd64
      dist: focal
      go: 1.23.x
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      go: 1.23.x
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      go: 1.23.1
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      go: 1.23.0
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      go: 1.22.7
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version


#    - stage: build
#      if: type = push
#      os: osx
#      osx_image: xcode14.2
#      go: 1.23.1
#      env:
#        - azure-osx
#      git:
#        submodules: false # avoid cloning ethereum/tests
#      script:
#        - ln -sf /Users/travis/gopath/bin/go1.23.1 /usr/local/bin/go
#        - go version
