language: go
dist: focal
os: linux
go_import_path: github.com/ethereum/go-ethereum
jobs:
  include:
    - stage: build
      if: type = push
      os: linux
      arch: arm64
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - ls -la /Users/travis/gopath/bin/
        - go version
