language: go
go_import_path: github.com/ethereum/go-ethereum
jobs:
  include:
    - stage: build
      if: type = push
      os: linux
      arch: amd64
      dist: focal
      go: 1.23.x
      env:
        - docker
      services:
        - docker
      git:
        submodules: false # avoid cloning ethereum/tests
      before_install:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
      script:
        - go version

    - stage: build
      if: type = push
      os: linux
      arch: arm64
      dist: focal
      go: 1.23.1
      env:
        - docker
      services:
        - docker
      git:
        submodules: false # avoid cloning ethereum/tests
      before_install:
        - export DOCKER_CLI_EXPERIMENTAL=enabled
      script:
        - go version


    - stage: build
      if: type = push
      os: osx
      osx_image: xcode14.2
      go: 1.23.1
      env:
        - azure-osx
      git:
        submodules: false # avoid cloning ethereum/tests
      script:
        - rm /Users/travis/gopath/bin/go && ln -s /Users/travis/gopath/bin/go1.23.1 /Users/travis/gopath/bin/go && go version
        - command -v go
        - $(command -v go) version
        - ls -la `command -v go`
        - which go
        - $(which go) version
        - ls -la `which go`
        - which go1.23.1
        - go version
